config/routes.rb
Rails.application.routes.draw do
  # get 'departments/index'
  # get 'departments/create'
  # get 'departments/new'

  # index
  # get '/employees', to: "employees#index"
  resources :employees
  resources :departments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :manager, foreign_key: :manager_id, class_name: "Employee"
  has_many :employees

  validates :head_count, numericality: { only_integer: true }
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :start_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
    # render json: @departments
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      @employees = Employee.all
      render :new
    end
  end

  def new
    @department = Department.new
    @employees = Employee.all
  end

  def show
  end

  def edit
    @employees = Employee.all
  end

  def update
    @department.update(department_params)

    redirect_to departments_path
  end

  def destroy
    @department.delete

    redirect_to departments_path
  end

  private

  #whitelisting what params we take in
  def department_params
    params.require(:department).permit(:name, :head_count, :manager_id)
  end

  def set_department
    @department = Department.find(params["id"])
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path
    else
      @departments = Department.all
      render :new
    end
  end

  def new
    @employee = Employee.new
    @departments = Department.all
  end

  def show
  end

  def edit
    @departments = Department.all
  end

  def update
    @employee.update(employee_params)

    redirect_to employees_path
  end

  def destroy
    @employee.delete

    redirect_to employees_path
  end

  private

  def employee_params
    params.require( :employee).permit(:name, :start_date)
  end

  def set_employee
    @employee = Employee.find(params["id"])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
  <% if !@department.errors.empty? %>
    <ul style="background-color: pink; border-radius: 0.5rem; padding: 0.5rem; list-style-type: none;">
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :head_count, "Head Count" %>
    <%= f.number_field :head_count %>

    <%= f.label :manager_id %>
    <%= f.collection_select :manager_id, @employees, :id, :name %>
    
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<%= render "form" %>

app/views/departments/index.html.erb
<ul>
    <% @departments.each do |department| %>
        <li>
            <%= department.name %>
        </li>
    <% end %>
</ul>

<a href="<%= new_department_path %>">Create Department</a>
<%= link_to  "Create Department", new_department_url %>

app/views/departments/new.html.erb
<%= render "form" %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<h3><%= @department.manager.name %></h3>

<%= link_to  "Edit Department", edit_department_path(@department) %>
<%= button_to "Delete", department_path(@department), method: :delete %>

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
  <% if !@employee.errors.empty? %>
    <ul style="background-color: pink; border-radius: 0.5rem; padding: 0.5rem; list-style-type: none;">
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :start_date %>
    <%= f.date_field :start_date %>

    <%= f.label :department_id %>
    <%= f.collection_select :department_id, @departments, :id, :name %>

    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<%= render "form" %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<ul>
  <% @employees.each do |employee| %>
    <li><%= employee.name %></li>
  <% end %>
</ul>

app/views/employees/new.html.erb
<%= render "form" %>

app/views/employees/show.html.erb
<%= @employee.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DenverTcfRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>